name: notify 

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Publish Release Frontend Docker image"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: ping host
        shell: bash
        run: |
          count=5
          while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "ping success"
          
      - name: call webhook
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          method: POST
